updated: '2025-05-26T16:53:51'
metric: 1.5662031691098768
params:
  n_estimators: 400
  cap_depth: false
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 11
  bootstrap: true
  max_samples: 1.0
  criterion: absolute_error
  ccp_alpha: 1.2167748107168915e-06
  oob_score: true
