updated: '2025-05-27T01:47:13'
metric: 0.5996480737381522
params:
  n_estimators: 450
  cap_depth: false
  min_samples_split: 6
  min_samples_leaf: 2
  max_features: 7
  bootstrap: false
  criterion: absolute_error
  ccp_alpha: 9.537775465873154e-06
