updated: '2025-05-26T21:03:21'
metric: 0.602000265002052
params:
  n_estimators: 900
  cap_depth: false
  min_samples_split: 6
  min_samples_leaf: 2
  max_features: 11
  bootstrap: true
  max_samples: 0.5
  criterion: absolute_error
  ccp_alpha: 8.45982235501033e-05
  oob_score: true
