updated: '2025-05-24T21:19:19'
metric: 0.8284886083457236
params:
  n_estimators: 3000
  cap_depth: false
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 3
  bootstrap: false
  criterion: absolute_error
  ccp_alpha: 1.698347150346809e-05
